---
# You get at this from the browser with something like:
# /?googly.js or /?googly.js=test
# Append .log for the log from the last compile.  If it contains
# the options help from the compiler, you have an error in this file.
# Append .map for the source map from the last compile.
# Using .map or .log without a build type gets you the results from
# the last compile job run but this information is retained uniquely for
# each build and type so you can be explicit: /?googly.log=build
googly:
  # You can use every option that compiler.jar supports.  Even the ones that
  # print to the console since you can simply view /?googly.log.
  # See all options with: java -jar compiler.jar --help
  # Options are passed to the compiler with very few modifications:
  # 1. --js_output_file is set to a temp file if none is specified.
  # 2. --create_source_map is set to a temp file if none is specified.
  # 3. --js entries are appended to satisfy the require namespaces.
  # If you explicitly set js_output_file and create_source_map without
  # any require namespaces, absolutely nothing will be changed.
  # The arrays are flattened before use so get creative with the syntax.
  # You may also embed Ruby: <%= Time.now %>
  require:
    # Require is special and always the default: /?googly.js == /?googly.js=require
    # It generates a list of goog.require() statements instead of compiled code.
    # It accepts an array of namespaces instead of compiler options.
    - googly.test
    - goog.editor.Field
  test: &base_options
    # The developers work in 'test' and in 'require'.
    - [--compilation_level, ADVANCED_OPTIMIZATIONS]
    - [--warning_level, VERBOSE]
  build: 
    # Perhaps you are process driven or have a build team.
    - *base_options
    - [--js_output_file, ./public/javascripts/googly.js]
  concat:
    # Not specifing a compilation_level will generate a concatenation.
    # The only supported option is --js_output_file which is optional.
    # Trying to get the .map for this will net you a 404.
    # It will generate a timestamped .log for those who like.
  debug:
    # When things get ugly
    - *base_options
    - [--debug, true]
    - [--formatting, PRETTY_PRINT]
    - [--formatting, PRINT_INPUT_DELIMITER]
    

myjqexperiment.js:
  # Require is optional.  Without it we must set which filenames to compile.
  # If there is only one build type, it becomes the default.  But two
  # or more build types and no require causes 404 on: /?myjqexperiment.js
  test:
    - [--compilation_level, ADVANCED_OPTIMIZATIONS]
    - [--warning_level, QUIET]
    - [--externs, spike/jquery.externs]
    - [--js, spike/common.js]
    - [--js, spike/widget_test_3.js]
