---
googly:
  require:
    - googly.test
    - goog.editor.Field
  test: &base_options
    - [--compilation_level, ADVANCED_OPTIMIZATIONS]
    - [--summary_detail_level, 3]
    - [--warning_level, VERBOSE]
  concat:
  debug:
    - *base_options
    - [--debug, true]
    - [--formatting, PRETTY_PRINT]
    - [--formatting, PRINT_INPUT_DELIMITER]
  simple:
    - *base_options
    - [--compilation_level, SIMPLE_OPTIMIZATIONS]
